---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/resources
  label: Resources
  create: all
  match: "**/*"
- type: directory
  path: content/blog
  label: Blog posts
  create: all
  match: "**/*"
upload_dir: static/images
public_path: "/images"
front_matter_path: "/images"
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - CI=true
  preview_output_directory: public
  install_dependencies_command: npm run forestry:install
  preview_docker_image: node:15.12.0-alpine3.13
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
